---
- name: Download local binaries
  get_url:
    checksum: "{{ item.checksum }}"
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop:
    - url: https://github.com/stedolan/jq/releases/download/jq-{{versions.jq.version}}/jq-linux64
      checksum: "{{ versions.jq.checksum }}"
      dest: "/usr/bin/jq"
      mode: u+x

- name: Install non-enterprise apt source
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    line: deb http://download.proxmox.com/debian buster pve-no-subscription
    state: present

- name: Remove enterprise apt repository
  ansible.builtin.replace:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    regexp: ^deb https\://enterprise\.proxmox\.com/debian/pve buster pve-enterprise$
    replace: "#deb https://enterprise.proxmox.com/debian/pve buster pve-enterprise"

- name: Upgrade the OS (apt-get dist-upgrade)
  apt:
    upgrade: dist

- name: install prereq packages
  ansible.builtin.apt:
    name: python3-pip

- name: install prereq packages
  ansible.builtin.pip:
    name: proxmoxer